Fix/sort by id
campudus/tableaux-frontend pull request #267
Opened 2021-06-29 11:27 UTC by smnhgn

# Submit a pull request

Please make sure the following is true:

- [x] This is not a duplicate of another PR
- [x] The correct target branch selected?
- Breaking changes
  - [x] No existing features have been broken (without good reason)
  - [ ] PR introduces breaking changes
- [x] Commit messages are meaningful
- [x] The behaviour is as the documentation describes, or you updated the docs
- Tests
  - [ ] Tests have been added/updated for new/modified unit-testable functions/helpers
  - [x] Test were run and did pass
- [x] The linter was run and did pass

## PR details

Fix für [#926](https://app.activecollab.com/116706/projects/2/tasks/26066) Kommentare

2021-06-29 11:40 UTC, hermann-p requested changes

2021-06-29 11:40 UTC, hermann-p commented on src/app/constants/TableauxConstants.js
> +    identifier: true,
Identifier muss `false` sein - das ist eine Prop, die im Backend das Aggregieren der Concat-Column triggert.

2021-06-29 11:40 UTC, hermann-p commented on src/app/components/contextMenu/ColumnContextMenu.jsx
>        !f.contains(column.kind, PROTECTED_CELL_KINDS);
Wäre es evtl. sinnvoll, die Metaspalte zu PROTECTED_CELL_KINDS hinzuzufügen? Ich hab nicht mehr im Kopf was durch diese Variable sonst noch getriggert wird...

2021-06-29 11:49 UTC, smnhgn commented on src/app/components/contextMenu/ColumnContextMenu.jsx
>        !f.contains(column.kind, PROTECTED_CELL_KINDS);
Die MetaSpalte für die RowId ist vom kind "numeric", d.h. nach meinem Verständnis wären dann alle Columns vom kind "numeric" nicht mehr editable (was ja nicht sein sollte).

Die Prop "isMetaColumn" habe ich gerade nur für diesen Zweck aufgenommen.
Ein anderer Weg wäre natürlich für diese MetaSpalte einen komplett eigenen column kind zu definieren und dann damit zu arbeiten. Nur entgeht einem dann evtl. Funktionalität die für den kind "numeric" aktuell bereits enthalten ist.

2021-06-30 08:38 UTC, hermann-p approved these changes

2021-06-30 10:10 UTC, merged