Performance/link overlay
campudus/tableaux-frontend pull request #306
Opened 2022-07-11 14:08 UTC by hermann-p

# Submit a pull request

## Please make sure the following is true:

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

## Summary

- Decrease display value generation from ~5s to ~0.7s
- Cache display values to decrease search to 50-100ms
- Debounce search input to 500ms; is this still required?

## Demo

This also uses the [backend performance PR](https://github.com/campudus/tableaux/pull/248) for better load time on opening overlay.

https://user-images.githubusercontent.com/7766378/178281740-a84b7440-0337-45e5-8ff1-2c66f094f808.mp4

2022-07-12 10:27 UTC, zingmane reviewed
Sieht soweit gut aus. Ich hab nicht erkennen können, wo genau das Bottleneck jetzt eigentlich genau war. Die Iterationen sind ja nicht weniger geworden. Außer dass jetzt ein `Set` verwendet wird und die search function in den state kommt, seh ich keine großen Unterschiede.

Wär vll. auch für ein bearly interessant?

2022-07-13 08:14 UTC, hermann-p commented on src/app/helpers/functools.js
> +
Ist ganz nützlich zu haben, falls man mal wieder Bottlenecks hat, deswegen habe ich sie wieder gelöscht. Ich würde sie nicht ständig im Build haben wollen, weil Logging ja auch langsam ist.

2022-07-13 08:53 UTC, Zwergal requested changes

2022-07-13 08:53 UTC, Zwergal commented on src/app/components/cells/link/LinkOverlayCache.jsx
> +    f.debounce(500, fn => setFilterFn(f.always(fn))),
**[suggestion]** Debounce-Millisekunden sind ja schwer pauschal zu definieren. Ich habe das Gefühl, dass 500ms hier etwas zu viel sind. Kommt aber drauf an wie man sucht. Tippt man was ein könnte es ok sein, copy&pasted man z.b. eine Artikelnummer ist es zu viel.

Ich wäre trotzdem für eine Anpassung auf 400ms. Was denkst Du?

2022-07-13 09:12 UTC, hermann-p commented
Da sind ein paar Sachen passiert:
- Listensuche gegen Set-Lookup in der Unterscheidung verlinkt-verfügbar - O(n*m) zu O(n), allerdings bei einer sehr kleinen Liste, das ist eher Liebhaberei
- Listensuche gegen Map-Lookup im anfügen der Displayvalues - O(n*n) zu O(n) (hier: ca. 5s zu gut 500ms). Hier bleibt noch das Anfügen der Displayvalues an die Links der Zeitfresser. Man könnte die Lookup-Map auch noch mit `useMemo` cachen, aber die durchschnittliche Aufbauzeit lag bei 6ms, das habe ich jetzt mal in Kauf genommen. Ich habe auch getestet, ob es an der Stelle vielleicht sinnvoll wäre die Linkwerte mutierend zu ergänzen. Der Performanceunterschied war allerdings im einstelligen Millisekundenbereich, also praktisch gar nicht messbar, darum hab ich es so gelassen. Das sind nun mal einfach 25k Schreibvorgänge.
- Caching (`useMemo`) der Links mit aggregierten Displayvalues in Abhängigkeit von Änderungen im Displayvalues-Reduxstore spart auch die 500ms-Aktion pro Render nach dem initialen Abholen der foreign rows. Ein klassischer Tausch Speicher gegen Laufzeit.

Somit bleiben nur noch Sortierung und Stringsuche in 25k Werten übrig, das ist je nach Lust und Laune des Browsers bei mir im Firefox zwischen 30 und 200ms. Natürlich könnte man noch hingehen und eine Trie-basierte Suche oder sowas einbauen, aber das wäre wieder viel Speicher und initialisierungszeit in allen Linkoverlays für einen Gewinn, den man nur in dem einen Sonderfall mit den sehr vielen Elementen nutzen kann, und man müsste statt der überall in der GRUD verwendeten Suche zwei neue Methoden bauen, die die selben Ergebnisse liefern...

2022-07-14 06:18 UTC, hermann-p commented on src/app/components/cells/link/LinkOverlayCache.jsx
> +    f.debounce(500, fn => setFilterFn(f.always(fn))),
Auf meinem Zettel hier steht "Debounce-Value mit Leuten diskutieren, die das Ding benutzen weil vermutlich zu hoch" -- ich bin da für eine Anpassung offen.

2022-07-14 09:41 UTC, hermann-p commented on src/app/components/cells/link/LinkOverlayCache.jsx
> +    f.debounce(500, fn => setFilterFn(f.always(fn))),
Ich warte mal auf ein Usability-Feedback von @McHunkyTrunk, vielleicht kommt da was brauchbares bei rum

2022-07-15 08:12 UTC, McHunkyTrunk commented
@hermann-p Wenn man im Link-Overlay einen Link auswählt, wird er offenbar zwar schon im Backend gespeichert und später in der Zelle angezeigt, jedoch nicht direkt in die Liste der ausgewählten Links im Overlays aufgenommen:
![image](https://user-images.githubusercontent.com/3919702/179181838-c1d089de-2612-458e-978e-779df8a18850.png)

2022-08-10 08:41 UTC, McHunkyTrunk approved these changes
400ms Debounce fühlen sich gut an. 👍

2022-08-10 09:20 UTC, Zwergal approved these changes

2022-08-10 09:22 UTC, merged