Taxonomy/styles and review
campudus/tableaux-frontend pull request #320
Opened 2022-10-21 07:02 UTC by hermann-p

# [Taxonomy] Final touches

2022-10-24 15:10 UTC, Zwergal requested changes

2022-10-24 15:10 UTC, Zwergal commented on src/app/components/taxonomy/TaxonomyTable.jsx
> +const mustInvertPopup = event => {
[**Minor**] bitte hier noch kommentieren, was genau ausgerechnet wird und warum. Kann es auf Anhieb noch nicht nachvollziehen, warum Höhe * 0,75 z.B..

2023-03-01 19:09 UTC, CoffeeGinger commented
Die Suche funktioniert nur einmal nach dem ersten load, danach werden keine Nodes mehr aufgeklappt wenn ich in der Suche ein Element auswähle.
Siehe nachfolgendes Gif.
file:///home/thimo/Videos/taxonomy_search_bug.gif

2023-03-01 19:11 UTC, CoffeeGinger submitted a review, later dismissed
Code sieht gut aus, nur die Sache mit der Suche passt noch nicht.

2023-03-01 19:16 UTC, CoffeeGinger commented
Wenn man einen Link löscht, scheint eine Übersetzung zu fehlen, siehe Screenshot.
![image](https://user-images.githubusercontent.com/40287903/222241700-4a4d318d-9378-4479-8bf9-0203ebbf76db.png)

2023-03-01 19:19 UTC, CoffeeGinger commented
Wenn ich ein Item lösche und es woanders zuweisen  möchte, stirbt das Frontend einfach.Siehe nachfolgendes Gif.
![delete_reassign_taxonomy_link](https://user-images.githubusercontent.com/40287903/222242424-015e892e-413f-4072-9a61-317da5897caa.gif)

2023-03-02 07:34 UTC, Zwergal commented
> Wenn ich ein Item lösche und es woanders zuweisen möchte, stirbt das Frontend einfach.Siehe nachfolgendes Gif.

Das ist meiner Meinung nach schon von vorne herein falsch, dass man beim löschen nochmal etwas neu verknüpfen kann:
![SCR-20230224-oam](https://user-images.githubusercontent.com/1858670/222361509-ae180fa5-a751-415e-94b7-8f230379905a.png)

2023-03-02 07:46 UTC, Zwergal commented
Anzeigefehler siehe Bild:
![SCR-20230301-om9](https://user-images.githubusercontent.com/1858670/222363958-44874d4f-ffc2-4db2-a985-e566ffcad417.png)

2023-03-02 07:56 UTC, Zwergal commented
Bei leeren Kategorien fehlt der statische Screen:
![Empty-categories](https://user-images.githubusercontent.com/1858670/222366133-c7fb0924-0a8b-4bca-8f8d-e65a1f852b60.png)

Design:
![image](https://user-images.githubusercontent.com/1858670/222366266-584d7450-2e1d-4160-979b-936c85e45bed.png)

2023-03-02 07:57 UTC, Zwergal commented
Suche sollte bei einer leeren Kategorie disabled sein:
![search-disabled](https://user-images.githubusercontent.com/1858670/222366380-7f7e6868-3624-4afa-88d4-5e2d977ad911.png)

Design:
![image](https://user-images.githubusercontent.com/1858670/222366428-a7e1144a-309f-4af2-9814-53604863485f.png)

2023-03-02 07:57 UTC, Zwergal commented
Border-radius ist zu viel (8 statt 4px):
![border-radius](https://user-images.githubusercontent.com/1858670/222366524-7e4a223e-c985-49d3-a0c9-0dc194e4107d.png)

Design:
![image](https://user-images.githubusercontent.com/1858670/222366567-ca4f14ec-8e7a-4e4e-a124-d900a83ee6ae.png)

2023-03-02 09:16 UTC, hermann-p commented
> Die Suche funktioniert nur einmal nach dem ersten load, danach werden keine Nodes mehr aufgeklappt wenn ich in der Suche ein Element auswähle. Siehe nachfolgendes Gif. [..]

Das kann ich nicht nachstellen. Hast du irgendwas besonderes getan?

2023-03-02 11:00 UTC, hermann-p commented
> > Das kann ich nicht nachstellen. Hast du irgendwas besonderes getan?
> 
> Nicht das ich wüsste. Das Backend ist der aktuelle Master, und der lokale branch ist up to date mit dem origin. Das ganze läuft mit Auth enabled und einem user der die dev Rolle hat. Getestet in Firefox mit Version 110.0.1. Frontend wird gestartet mit nvm use && npm ci && npm run build && npm run start.

Das ist seltsam. Hier kann ich mit der Suche immer wieder nach Belieben durch alle Elemente springen, egal ob ich den Tree zwischendrin schließe oder offen lasse... ich sag mal "Thimo hat Special-Setup" *lol*
Aber im Ernst, es läuft hier im Chromium und im Firefox, und ich hatte es schon mit Julia zusammen getestet, bei ihr gings auch. Kann sonst jemand diesen Fehler produzieren?

2023-03-02 11:07 UTC, Zwergal commented
> > > Das kann ich nicht nachstellen. Hast du irgendwas besonderes getan?
> > 
> > 
> > Nicht das ich wüsste. Das Backend ist der aktuelle Master, und der lokale branch ist up to date mit dem origin. Das ganze läuft mit Auth enabled und einem user der die dev Rolle hat. Getestet in Firefox mit Version 110.0.1. Frontend wird gestartet mit nvm use && npm ci && npm run build && npm run start.
> 
> Das ist seltsam. Hier kann ich mit der Suche immer wieder nach Belieben durch alle Elemente springen, egal ob ich den Tree zwischendrin schließe oder offen lasse... ich sag mal "Thimo hat Special-Setup" _lol_ Aber im Ernst, es läuft hier im Chromium und im Firefox, und ich hatte es schon mit Julia zusammen getestet, bei ihr gings auch. Kann sonst jemand diesen Fehler produzieren?

Ja, ich habe genau den gleichen Fehler. Ist auch grad auf dem BikeParts Testsystem deployed und da kann ich es nachstellen: https://bikepartstest.campudus.com/de/tables/721

2023-03-02 11:45 UTC, hermann-p commented
> > > > Das kann ich nicht nachstellen. Hast du irgendwas besonderes getan?
> 
> Ja, ich habe genau den gleichen Fehler. Ist auch grad auf dem BikeParts Testsystem deployed und da kann ich es nachstellen: https://bikepartstest.campudus.com/de/tables/721

Ah... der Fehler tritt nur dann auf, wenn man nochmal versucht, ein Kind des selben Parents zu öffnen, das vorher offen war, nachdem man den Baum geschlossen hat...

2023-03-02 13:48 UTC, Zwergal commented
> > Wenn ich ein Item lösche und es woanders zuweisen möchte, stirbt das Frontend einfach.Siehe nachfolgendes Gif.
> 
> Das ist meiner Meinung nach schon von vorne herein falsch, dass man beim löschen nochmal etwas neu verknüpfen kann: ![SCR-20230224-oam](https://user-images.githubusercontent.com/1858670/222361509-ae180fa5-a751-415e-94b7-8f230379905a.png)

Das geht immer noch. Nur funktioniert es jetzt. Dadurch geht aber alles kaputt, da man danach einen zyklischen Linkverlauf hat.
Wie ich geschrieben habe, sollte da gar nichts auftauchen. Liegt das evtl. daran, dass die Link-Column falsch eingestellt ist?

2023-03-02 13:54 UTC, Zwergal commented on src/app/components/taxonomy/TaxonomyDashboard.jsx
> +      href={`mailto://${supportDetails.email}`}
Hier sind die // zu viel.
```suggestion
      href={`mailto:${supportDetails.email}`}
```

2023-03-03 15:21 UTC, CoffeeGinger approved these changes

2023-03-06 12:42 UTC, Zwergal approved these changes

2023-03-06 14:28 UTC, merged