Feature: Filter for empty items
campudus/tableaux-frontend pull request #340
Opened 2023-08-04 12:55 UTC by hermann-p

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

## Reason for this PR

- Refaktor der FilterRow-Komponente
- Refaktor der Zellwert-Filterfunktion
- Ersetzt ein paar Strings durch schon vorhandene Konstanten
- Fügt einen Filter für leere Werte hinzu

2023-08-04 13:13 UTC, Zwergal commented on src/app/components/table/RowFilters.js
> +  console.log({ searchFunction });
[Minor] Remove debug log

2023-08-09 14:31 UTC, hermann-p commented on tests/rowFilters/rowFilters.test.js
> +    expect(filterResult.map(idx => sparseRows.rows[idx].id)).toEqual([colId]);
Das liegt am Testdatensatz. Das ist eine Tabelle mit 23 Spalten und 23 Zeilen, und in der Zeile mit ID=i ist in der Spalte mit ID=1 der Eintrag leer.
Aber hast Recht, das könnte man im Test noch kommentieren.

2023-08-09 14:32 UTC, hermann-p commented on src/locales/en/table.json
> +    "is_empty": "Is empty"
Das ist leider historisch uneinheitlich.

2023-08-09 14:41 UTC, hermann-p commented on src/app/components/header/filter/FilterRow.jsx
> +    if (onRemoveFilter) onRemoveFilter();
Kannst du mir erklären, warum der ternäre Ausdruck besser ist? Oder das beliebte `callback && callback()`?

Meiner Meinung nach ist das hier halt mal ein Statement und kein Ausdruck, von daher sind sowohl das Ternary als auch der JS-Hack falsch, weil beides _eigentlich_ Ausdrücke sind.

Auch sehe ich die Notwendigkeit einer zusätzlichen Klammerung nicht, wenn der Body nur ein kurzer Aufruf ist, so dass es keine verwirrenden Zeilenumbrüche gibt, aber das mag Gewohnheitssache sein.

2023-08-09 14:57 UTC, hermann-p commented on src/app/components/table/RowFilters.js
> +  const { columnId, colId } = settings;
Da stimme ich dir zu, kenne aber die genauen Gründe dafür auch nicht mehr; evtl. ist das ein Fallback dafür, dass irgendwann mal ein falscher Typ Fehler verursacht hat? Ich habe diesen Teil aus den anderen Filtern einfach mal übernommen, anstatt noch mehr zu refaktorieren und dadurch evtl. weitere Fehler einzubauen.

2023-08-10 02:10 UTC, McHunkyTrunk commented on src/app/components/header/filter/FilterRow.jsx
> +    if (onRemoveFilter) onRemoveFilter();
Die Erklärung ist ganz einfach: Die Kürze - nachdem aus dem gleichen Grund ja auch die Klammern weggelassen wurden ;-) Ob das Ausdrücke oder Statements sind, gibt es hier wohl kaum Nachteile oder Risiken. War aber tatsächlich nur ein Vorschlag, kein Änderungswunsch. 👍

2023-08-10 06:48 UTC, hermann-p commented on src/locales/en/table.json
> +    "is_empty": "Is empty"
Hab auch dafür mal einen Mini-Task angelegt.

2023-08-16 10:35 UTC, McHunkyTrunk approved these changes

2023-08-16 10:36 UTC, McHunkyTrunk commented
Im Test-System ist mir nichts Verdächtiges aufgefallen, funktioniert wie erwartet.

2023-08-16 10:53 UTC, McHunkyTrunk requested changes
Muss den Approve zurücknehmen, da mir gerade sporadisch einige Sachen aufgefallen sind:

1. "Wert leeren" Icon erscheint bereits, wenn man den Dialog öffnet:

<img width="1261" alt="image" src="https://github.com/campudus/tableaux-frontend/assets/3919702/c53d568e-dd15-463c-a6f9-1f8f9f69eedc">


2. Titel für allgemeine Filter wird nicht übernommen. Scheint aber dennoch zu funktionieren:

<img width="1202" alt="image" src="https://github.com/campudus/tableaux-frontend/assets/3919702/b2e61ac5-55af-4406-a3e6-4da2322bea6d">

2023-08-17 08:03 UTC, hermann-p commented on src/app/components/header/filter/FilterRow.jsx
> +
```suggestion
```

2023-08-17 08:40 UTC, McHunkyTrunk approved these changes

2023-08-17 08:49 UTC, merged