Feature: Open some attachments in new tabs
campudus/tableaux-frontend pull request #341
Opened 2023-08-09 12:31 UTC by hermann-p

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

2023-08-10 08:55 UTC, McHunkyTrunk requested changes

2023-08-10 08:55 UTC, McHunkyTrunk commented on src/app/components/cells/link/LinkItem.jsx
> +    <Link className={className} to={url} onClick={handleOpenNewWindow}>
[SUGGESTION] Sollte `target="_blank"` als Prop nicht ausreichen statt dem Click-Handler?

2023-08-10 12:21 UTC, hermann-p commented on src/app/components/cells/link/LinkItem.jsx
> +    <Link className={className} to={url} onClick={handleOpenNewWindow}>
Wir nutzen hier teilweise sehr alte Paketversionen. Ich hatte das mit dem Target blank probiert; dann wird zwar ein neuer Tab geöffnet, aber gleichzeitig navigiert die GRUD zum Dashboard (der EntityView bleibt dabei offen).
Vielleicht gibt es noch eine Prop, mit der das auch verhindert werden kann, aber ich habe die noch nicht gefunden.

2023-08-16 12:34 UTC, McHunkyTrunk requested changes

2023-08-16 12:34 UTC, McHunkyTrunk commented on src/app/components/cells/link/LinkItem.jsx
> +  return ["png", "jpg", "gif", "html", "pdf", "webp"].includes(fileType);
[SUGGESTION] Ich würde noch die SVGs einschließen.
Beispiel:
https://pdc-test.bikeparts.grud.de/de/tables/14/columns/5/rows/61

2023-08-17 08:18 UTC, McHunkyTrunk approved these changes

2023-08-17 08:18 UTC, merged