AC-1023: Dependent links display error
campudus/tableaux-frontend pull request #344
Opened 2023-09-14 12:11 UTC by hermann-p

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

2023-09-14 14:48 UTC, Zwergal commented
Sieht an sich gut aus, da der Scroll-Bug nun nicht mehr vorhanden ist.

Nur die Scrollbalken passen überhaupt nicht.
- Vertikaler Balken ist falsch (zu "groß", sollte eigentlich kleiner sein da der Inhalt recht lange ist), da man in dem Beispiel recht weit scrollen kann.
- Horizontaler Balken sollte eigentlich gar nicht da sein. Der scrollt genauso weit wie der vertikale breit ist. Könnte daher sein dass der kommt weil es den vertikal Balken gibt. Evtl. muss da was von der Breite der Link-Elemente abgezogen werden.
![image](https://github.com/campudus/tableaux-frontend/assets/1858670/8cdd25da-2a9e-4297-895a-815ee3e3cbb3)

2023-09-14 14:49 UTC, Zwergal requested changes
Siehe Kommentar mit den Scrollbalken.

2023-09-25 06:51 UTC, hermann-p commented
Hm... das mit den Scrollbalken habe ich gar nicht gesehen... nach ein paar Tests habe ich festgestellt, dass das Problem nur im Chrome auftritt. Klingt nach Spaß beim Debugging...

2023-09-29 13:51 UTC, Zwergal approved these changes

2023-09-29 13:52 UTC, merged