feature/profile
campudus/tableaux-frontend pull request #348
Opened 2023-11-16 10:36 UTC by smnhgn

# Submit a pull request

## Please make sure the following is true:

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

2023-11-18 10:45 UTC, Zwergal commented
[Improvement] Der Button "Tabellenansicht zurücksetzen" erscheint aktuell immer. Auch wenn die Tabelle in Ihrem default-Zustand ist und gar nichts passiert wenn man zurück setzt.
Hier wäre es super, wenn der Button erst erscheint, sobald man eine Anpassung macht die vom default abweicht. (Filter/Sortierung setzen, Spalten ein/ausblenden, Spalten in der Größe verändern, Spalten Reihenfolge verändern)
<img width="600" alt="image" src="https://github.com/campudus/tableaux-frontend/assets/1858670/8ba02ec6-7e31-4e16-8574-9cb1e377220b">

2023-11-18 10:55 UTC, Zwergal commented
[Major] Habe ich die Einstellung "Spaltenansicht automatisch zurücksetzen", dann betrifft das nur die ein/ausgeblendeten Spalten. Die Sortierung der Spalten als auch die Größen bleiben bestehen. (Das gleiche gilt auch für den Button "Tabellenansicht zurücksetzen").
Ich hätte erwartet, dass sich die komplette Spaltenansicht auf default zurücksetzt, also auch die Spaltensortierung als auch die Spaltengrößen.
Die Beschreibung der globalen Einstellung ist da aber aktuell etwas verwirrend weil sie nur das ein/ausblenden beschreibt. Evtl. sollten wir das umbenennen auf "Ist diese Einstellung aktiviert, werden nach einem Tabellenwechsel alle individuellen Spalteneinstellungen zurückgesetzt."

Als Alternative könnte man das noch aufteilen in 2 Einstellungen, wenn man Spalteneinstellungen (Größe und Anordnung) und Spaltensichtbarkeit (was ist ein/ausgeblendet) getrennt steuern möchte.

<img width="615" alt="image" src="https://github.com/campudus/tableaux-frontend/assets/1858670/c360c6b8-a60c-4ab7-a7b3-6197d6ed15f8">

2023-11-18 11:03 UTC, Zwergal commented
[Major] Filter zurücksetzen funktionier nur, wenn man über das GRUD eigene Menü navigiert. Macht man einen Browser refresh oder öffnet die Tabelle in einem neuem Tab über einen Deep-Link, bleibt der Filter erhalten.
Erwartet wäre hier, dass der Filter entfernt wird, auch bei einem Browser refresh bzw. Deep-Link.
Siehe Gif:
![filter](https://github.com/campudus/tableaux-frontend/assets/1858670/5f90047c-255d-43f2-bdc2-c3d4b747a1da)

PS: Gleiches Verhalten gilt für Spaltenansicht und Sortierung zurücksetzen.

2023-11-18 11:12 UTC, Zwergal commented
[Minor] Bei kleinem Bildschirm kommt bei den Einstellungen eine Scrollbar direkt im Block für die Einstellungen. Wäre es hier nicht besser, wenn einfach der Browser hier das scrollen übernimmt und die "normale" Browserscrollbar kommt?

<img width="1494" alt="image" src="https://github.com/campudus/tableaux-frontend/assets/1858670/5ac008ab-234f-4c97-99e3-3dc7eb4bd31e">

2023-11-18 11:13 UTC, Zwergal requested changes
Der Code sieht für mich gut aus.
Funktional gibt es aber noch ein paar Kleinigkeiten.
Siehe dazu die einzelnen Kommentare mit Screenshots.

2023-11-21 12:21 UTC, smnhgn commented
@Zwergal @hermann-p 
Leider war die Herangehensweise über History eine Sackgasse.

Ich habe jetzt aber doch eine ganz gute Lösung gefunden:
Ich lege den ID-Filter für einen Navigations-Cycle mit in den LocalStorage und entferne ihn hinterher wieder.
Auf diese Weise bleiben auch die gespeicherten Filter für die jeweilige Tabelle erhalten.

Bitte nochmal testen :)

2023-11-28 07:27 UTC, hermann-p approved these changes
Schaut erst mal soweit ganz gut aus. Wenn @Zwergal alle seine Use-Cases abgedeckt sieht passt es für mich.

2023-11-28 10:45 UTC, Zwergal approved these changes

2023-11-28 10:46 UTC, Zwergal commented
Schaut auch für mich jetzt alles gut aus. Kann gemerged werden! 🎉

2023-11-29 09:09 UTC, merged