Feature: Offer to clear multi language cells when main content gets cleared
campudus/tableaux-frontend pull request #358
Opened 2024-01-22 15:24 UTC by hermann-p

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

## Summary

[AC#1008](https://app.activecollab.com/116706/projects/2?modal=Task-47563-2)

2024-01-23 10:21 UTC, Zwergal commented
@hermann-p 
1. Wie soll das Verhalten sein, wenn ein User die Hauptsprache löscht, aber nicht für alle Sprachen Schreibrecht hat?
"Zelle leeren" darf in dem Fall nicht möglich sein.

2. Bei welchen Zelltypen soll das Verhalten angewendet werden? Aktuell sind nur (Short-, Rich-)Textspalten mit einbezogen.
Generell bei allen Zelltypen. Macht eigentlich für alle Sinn, dass das möglich ist.

2024-01-24 10:28 UTC, hermann-p commented
@Zwergal 

>     2. Bei welchen Zelltypen soll das Verhalten angewendet werden? Aktuell sind nur (Short-, Rich-)Textspalten mit einbezogen.
>        Generell bei allen Zelltypen. Macht eigentlich für alle Sinn, dass das möglich ist.

Wir haben folgende Zelltypen:

- **text/richtext/shorttext:** multilang-fähig, leer wenn der Wert `""` ist. Ist im auto-clear schon mit drin.
- **link:** nicht multilang-fähig, leer wenn keine Links. Kein Auto-clear möglich.
- **numeric/integer:** multilangfähig, hat keine wirkliche Definition von leer - oder wollen wir `0` als leer betrachten? Auto-clear vermutlich irreführend.
- **boolean:** multlangfähig, wann leer? Auto-clear meiner Meinung nach nicht möglich.
- **concat/status/group:** multilangfähig, nicht direkt schreibbar.
- **attachment:** evtl. multilangfähig? Allerdings ist das ein manueller Pick von einem Eintrag nach dem anderen, soll da wirklich beim entfernen eines Attachments die Frage kommen? Auto-clear möglich, aber da muss ich noch überzeugt werden, das zu machen.
- **date/datetime:** theoretisch multilangfähig, wird praktisch nicht genutzt. Auto-clear möglich.
- **currency:** multi-country-fähig, hat aber beim feststellen von "leer" das selbe Problem wie Zahlen. Auto-clear ebenfalls vmtl. irreführend.

Wenn ich mir das so ansehe würde ich das implizite leeren von Zellen noch für Datumsfelder umsetzen, bei allen anderen sind wir vermutlich besser bedient, das nur explizit auszuführen (Backspace/Delete auf markierter Zelle bzw. Menüaktionen).

2024-01-24 11:37 UTC, hermann-p commented
Ok, ich hab mir die Requests nochmal angeschaut.

- Die Eingaben in Zahlfeldern können gelöscht werden, dann schicken wir ein `null` stattdessen ans Backend. Hab ich also eingabaut.
- Wenn man Preise leert schicken wir `0` ans Backend; da die Redux-Action nur angestoßen wird, wenn der Wert vorher anders war, können wir das wohl auch als "leer"-Signal werten.


| Typ                     | multilang möglich? | leer wenn             | implizites leeren? |
|-------------------------|--------------------|-----------------------|--------------------|
| text/richtext/shorttext | Ja                 | `""`                  | umgesetzt          |
| link                    | Nein               | `[]`                  | nein               |
| numeric/integer         | Ja                 | `null`                | umgesetzt          |
| boolean                 | Ja                 | ???                   | wie? eher nein     |
| concat/status/group     | Ja                 | nicht schreibbar      | nein               |
| attachment              | Ja?                 | `[]` - aber sinnvoll? | eher nein         |
| date/datetime           | Ja                 | kein valides Datum    | umgesetzt          |
| currency                | Ja                 | `0`                   | umgesetzt       |

2024-01-24 13:59 UTC, Zwergal commented
> Ok, ich hab mir die Requests nochmal angeschaut.
> 
> * Die Eingaben in Zahlfeldern können gelöscht werden, dann schicken wir ein `null` stattdessen ans Backend. Hab ich also eingabaut.
> * Wenn man Preise leert schicken wir `0` ans Backend; da die Redux-Action nur angestoßen wird, wenn der Wert vorher anders war, können wir das wohl auch als "leer"-Signal werten.
> 
> Typ	multilang möglich?	leer wenn	implizites leeren?
> text/richtext/shorttext	Ja	`""`	umgesetzt
> link	Nein	`[]`	nein
> numeric/integer	Ja	`null`	umgesetzt
> boolean	Ja	???	wie? eher nein
> concat/status/group	Ja	nicht schreibbar	nein
> attachment	Ja?	`[]` - aber sinnvoll?	eher nein
> date/datetime	Ja	kein valides Datum	umgesetzt
> currency	Ja	`0`	umgesetzt
@hermann-p 
Bei boolean bin ich bei Dir, gibt ja keine Definition von leer. Evtl. false, aber das ist nicht klar.
Bei concat/status/group macht es auch Sinn, dass es dort nicht geht.
Bei attachment können wir es im 1. Schritt erstmal weglassen.
Nur bei link sehe ich es schon als sinnvoll. Definition von leer ist keine Verlinkung. Multilang gibt es nicht, daher braucht es keinen Dialog, aber ein "Zelle leeren" wäre trotzdem gut, wenn man damit min einem Klick alle Links entfernen kann. Oder ist das so schon möglich?

2024-01-24 14:38 UTC, hermann-p commented
> @hermann-p Bei boolean bin ich bei Dir, gibt ja keine Definition von leer. Evtl. false, aber das ist nicht klar. Bei concat/status/group macht es auch Sinn, dass es dort nicht geht. Bei attachment können wir es im 1. Schritt erstmal weglassen. Nur bei link sehe ich es schon als sinnvoll. Definition von leer ist keine Verlinkung. Multilang gibt es nicht, daher braucht es keinen Dialog, aber ein "Zelle leeren" wäre trotzdem gut, wenn man damit min einem Klick alle Links entfernen kann. Oder ist das so schon möglich?

Die explizite Aktion "Zelle leeren" ist nicht Teil des PRs; hier geht nur um das implizite leeren von Multilang-Zellen, als Effekt vom setzen der Hauptsprache auf eine Definition von "leer" für den entsprechenden Zelltypen.

2024-01-24 14:51 UTC, Zwergal commented
@hermann-p Ah, jetzt bin ich dabei. Da war der falsche Task verlinkt im PR-Kommentar ;)

2024-01-25 12:46 UTC, McHunkyTrunk commented
Mein Senf zu den noch offenen Punkten:

- **boolean**: Macht meiner Meinung nach keinen Sinn, da `false` als tatsächlicher Wert erachtet werden kann.
- **concat/status/group**: Wie Max gesagt hat, ergibt es hier auch keinen Sinn, da wir es nicht direkt beschreiben können.
- **link und attachment**: Theoretisch wäre ja multilanguage sehr wohl denkbar, das Backend erlaubt und speichert ja auch aktuell die Konfiguration als `multilanguage: true`. Aber praktisch haben wir es aktuell im Frontend nicht umgesetzt. Daher auch hier eher ein Nein.

2024-01-25 13:32 UTC, hermann-p commented
> Mein Senf zu den noch offenen Punkten:
> 
>     * **boolean**: Macht meiner Meinung nach keinen Sinn, da `false` als tatsächlicher Wert erachtet werden kann.
> 
>     * **concat/status/group**: Wie Max gesagt hat, ergibt es hier auch keinen Sinn, da wir es nicht direkt beschreiben können.
> 
>     * **link und attachment**: Theoretisch wäre ja multilanguage sehr wohl denkbar, das Backend erlaubt und speichert ja auch aktuell die Konfiguration als `multilanguage: true`. Aber praktisch haben wir es aktuell im Frontend nicht umgesetzt. Daher auch hier eher ein Nein.

Das Backend speichert bei Links zwar "multilang: true", aber Linkzellen liefern (Stand Mitte 2023) immer nur einsprachige Werte zurück. Das war mal Grund eines fiesen History-Bugs (der Mitte 2023 entdeckt wurde).

2024-01-25 13:33 UTC, McHunkyTrunk commented
@hermann-p Vielleicht hängen die Sachen ja auch alle zusammen, s. auch Video im Anhang.

1. Es ist nicht möglich, numerische Werte einzutragen.
2. Bei `date` / `datetime` wird man direkt bei der Eingabe des "initialen" Werts für die Hauptsprache zum Löschen aufgefordert.
3. Auch dort: Es ist nicht möglich, für andere Sprachen einen anderen Wert einzutragen, er bleibt immer beim Wert der Hauptsprache.
4. Auch dort: Es ist nicht möglich, den Wert zu löschen.
5. Wenn man den Zellenwert für eine andere Sprache ändert und die Seite neulädt, hat sich die UI-Sprache auch mitgewechselt.
6. `currency` verhält sich total komisch, da ist überhaupt keine Eingabe möglich, und die Zelle der Hauptsprache verschwindet.

https://github.com/campudus/tableaux-frontend/assets/3919702/d3f4f7ee-6725-4b76-bc35-b9cfa315041b

2024-01-25 13:43 UTC, McHunkyTrunk requested changes

2024-01-25 13:43 UTC, McHunkyTrunk commented on src/locales/en/table.json
> +    "description": "This will clear the following value:"
[MINOR] `values`

2024-01-25 13:43 UTC, McHunkyTrunk commented on src/app/redux/actions/cellActions.js
> +    console.error("NO CELL OBJECT PASSED IN, using Fallback");
Wut? Wofür ist das hier? Um welchen Fallback geht es hier?

2024-01-29 11:30 UTC, hermann-p commented on src/app/redux/actions/cellActions.js
> +    console.error("NO CELL OBJECT PASSED IN, using Fallback");
Wir haben keine Typgarantie, daher wurden Zellen manchmal adressiert mit den Daten aus `cell` und manchmal direkt über `tableId, columnId, rowId`.
Zum testen der Übersetzungsberechtigung, des Zelltyps etc. brauche ich allerdings immer das `cell`-Objekt. Um nicht alles zu brechen habe ich entschlossen, erst mal den Error einzubauen, damit man noch etwaitige untergegangenen Übeltäter schnell identifizieren kann.

Der Fallback ist ein paar Zeilen drüber, `const cell = action.cell || { column: {id: columnId} }` usw

2024-01-29 11:32 UTC, hermann-p commented
Ich hab jetzt Bugfixes für die Wärungs- und die Datumszellen eingebaut. Leider waren beide Zelltypen so überkomplex aufgebaut (mehrfach vorgehaltene State, verschachtelte Updates etc.), dass es einfacher war sie einmal komplett zu rekatorisieren anstatt auf Fehlersuche zu gehen.

2024-02-15 09:00 UTC, hermann-p commented
Mittlerweile ausgeartet beinhaltet der Branch jetzt
- "Clear all"-Dialog
- Tasten/Menüeinträge um Zellen zu löschen
- Bugfixes zum Klick-Handling, die durch Multiselect eingeführt wurden
- Refaktorierungen einiger Zelltypen
- Bugfixes von alten Sachen, die uns beim testen der Klickhandler aufgefallen sind

2024-02-15 11:19 UTC, McHunkyTrunk commented
@hermann-p Round X. Fight.
1. Wenn ich versuche, eine Currency Zelle zu löschen, wird offensichtlich eine nicht-existierende Annotation Route aufgerufen:

```
No route found for path DELETE /tables/142/columns/8/rows/1/annotations/undefined
```

![image](https://github.com/campudus/tableaux-frontend/assets/3919702/22a082a2-5d62-461a-b6e9-75a89ee67ae9)

2024-02-15 11:27 UTC, McHunkyTrunk commented
@hermann Numero 2:
Wenn ich mehrere Werte eingetragen habe für eine Currency und eine Currency lösche (egal ob Deutsch oder nicht), kommt ein Bestätigungsdialog, und man muss teilweise mehrmals auf Abbrechen klicken, bis es durch ist. Siehe Video.

https://github.com/campudus/tableaux-frontend/assets/3919702/163ecd67-340f-458c-9967-90e917715694

2024-02-15 11:32 UTC, McHunkyTrunk commented
@hermann-p Wenn ich einen Zellenwert lösche für eine andere Sprache und sofort nach unten mit der Pfeiltaste navigiere, springt der Fokus teilweise mehrere Zeilen nach unten (anstatt nur 1). Siehe Video


https://github.com/campudus/tableaux-frontend/assets/3919702/0490a3b7-a754-4a86-bc3b-7ead8c399801

2024-02-15 11:40 UTC, McHunkyTrunk commented
@hermann-p (4) MCCP ist nun kaputt... Zum einen kann ich mir den kopierten Inhalt nicht mehr anzeigen lassen.

https://react.dev/errors/130?invariant=130&args%5B%5D=undefined&args%5B%5D=

```
Error: Minified React error #130
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.[missing argument]
```

Zum anderen Kannkann der Inhalt nicht eingefügt werden. Wenn man außerdem die Zeilen mit Shift markiert, werden Inhalte der anderen Zellen gehighlighted (als wenn man mehrzeiligen Text auswählen würde). Siehe Video.

https://github.com/campudus/tableaux-frontend/assets/3919702/8a3975a9-1d16-48fd-86f4-9c21ae90c50b

2024-02-15 12:16 UTC, hermann-p commented
> ~~@hermann-p (4) MCCP ist nun kaputt...~~

Korrektur: Copy-Paste ist für `ColumnKind.integer` nicht definiert.

2024-02-15 14:03 UTC, McHunkyTrunk commented
@hermann-p Der Bestätigungsdialog für andere Sprachen kommt beim Löschen nun auch, wenn es keine Einträge für andere Sprachen gibt. Können wir das so gestalten, dass er erst kommt, wenn es wirklich Werte in anderen Sprachen gibt?

2024-02-16 01:31 UTC, McHunkyTrunk commented
@hermann-p Ok, die aktuell Version scheint zumindest benutzbar zu sein. Ich würde an dieser Stelle den PR abschließen. Weitere / bestehende Bugs habe ich im AC notiert:
[#1059: BUG: Maus-Navigation ist nicht im Sync mit Tasten-Navigation.](https://app.activecollab.com/116706/projects/2/tasks/52558)
[#1060: BUG: Der Zellenwert einer Currency-Zelle darf gelöscht werden, wenn er undefined ist.](https://app.activecollab.com/116706/projects/2/tasks/52565)
[#1061: BUG: Die Shift-Markierung für MCCP highlightet zeilenübergreifend die Zelleninhalte.](https://app.activecollab.com/116706/projects/2/tasks/52572)

2024-02-17 01:30 UTC, merged