Allow setting decimal digits
campudus/tableaux-frontend pull request #388
Opened 2024-08-07 14:37 UTC by hermann-p

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

2024-08-07 15:18 UTC, Zwergal approved these changes
Code sieht gut aus. Habe es aber noch nicht manuell getestet.

2024-08-08 00:35 UTC, McHunkyTrunk requested changes
Für mich funktioniert es noch nicht 100%. Deployed auf BP Test.
- Thermopads: [Verpackungslänge](https://pdc-test.bikeparts.grud.de/de/tables/597/columns/7/rows/4) (`separator: false`) ✅
- Sättel: [Länge](https://pdc-test.bikeparts.grud.de/de/tables/233/columns/54/rows/5) (`separator: true`) 🚫

Siehe Video. Bei den Sätteln wird die Anzeige abgeschnitten, Bearbeitung geht.
Der einzige Unterschied der Spalten liegt im separator.

https://github.com/user-attachments/assets/3ee56a4c-bff6-49b3-9e4d-3a641ba7b95d

2024-08-08 06:04 UTC, hermann-p commented
In der Darstellung hat sich gar nichts geändert, nur bei der Eingabe wird statt hart an drei jetzt an `decimalDigits ?? 3` Stellen abgeschnitten. Ist die Länge `number` oder `integer`?

2024-08-08 07:14 UTC, McHunkyTrunk commented
@hermann-p Sind beide numeric. Aber wenn sich an der Darstellung nichts geändert hat, warum wird es für Thermopads dennoch in voller Länge angezeigt? Also eins von beiden Fällen ist fehlerhaft.

2024-08-08 08:15 UTC, hermann-p commented
Ist das Verhalten vor dem Change anders?

2024-08-08 10:20 UTC, McHunkyTrunk commented
@hermann-p Vor dem Change haben wir eh max 3 Stellen. Aktuell werden bei den Sätteln max. 3 Stellen angezeigt, bei Thermopads 10. Bearbeitbar sind alle Stellen.

2024-08-08 21:35 UTC, McHunkyTrunk commented
@hermann-p Mit der neuen Version lassen sich offensichtlich keine Tabellen anzeigen, die eine `numeric` Spalte beinhalten:

![image](https://github.com/user-attachments/assets/44672e7a-2d12-47f0-9cd8-0eef82f40d55)

2024-08-09 13:14 UTC, hermann-p commented
> @hermann-p Mit der neuen Version lassen sich offensichtlich keine Tabellen anzeigen, die eine `numeric` Spalte beinhalten:

Kannst du mir mal die Config der Tabelle schicken? Welche Langtags gibt in der GRUD?

2024-08-12 13:28 UTC, McHunkyTrunk approved these changes

2024-08-12 13:28 UTC, merged