AC#1024/fix columns in ColumnFilterPopup
campudus/tableaux-frontend pull request #402
Opened 2024-10-14 14:48 UTC by smnhgn

# Submit a pull request

## Please make sure the following is true:

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

2024-10-15 06:17 UTC, hermann-p requested changes
Das funktioniert nicht in allen Fällen. Grundsätzliches zur Logik habe ich im AC-Task dazu kommentiert. Kurzzusammenfassung: die erste Spalte ist immer diejenige, die den Datensatz identifiziert und darf niemals ausgeblendet werden. Deswegen ist es korrekter, alle Spalten außer der ersten im Dropdown darzustellen.

(Es kann nur maximal eine Concat-Spalte pro Tabelle geben, deren Name immer "ID" ist. So eine Spalte gibt es allerdings auch nur, wenn es mehr als eine Identifier-Spalte in der Tabelle gibt; in allen anderen Fällen wird entweder die Identifierspalte an die erste Stelle sortiert oder die erste Spalte zum Identifier "befördert")

Korrekterweise muss sichergestellt werden, dass die erste Spalte unter allen Umständen immer angezeigt werden muss.

2024-10-15 08:44 UTC, smnhgn commented
> Korrekterweise muss sichergestellt werden, dass die erste Spalte unter allen Umständen immer angezeigt werden muss.

Ich habe die Filterlogik nun so angepasst, dass die erste Spalte immer mitangezeigt wird.

2024-11-06 10:53 UTC, McHunkyTrunk approved these changes

2024-11-06 10:58 UTC, smnhgn commented
@hermann-p kannst du hier auch nochmal drüber schauen und ggf. approven, damit wir diesen PR auch mergen können?

2024-11-06 14:28 UTC, hermann-p approved these changes
Sollte passen, soweit ich das sehe

2024-11-06 14:30 UTC, merged