Re-calculate display values after loading archived data
campudus/tableaux-frontend pull request #412
Opened 2024-11-21 09:37 UTC by hermann-p

- [x] I gave the PR a meaningful name
- [x] I checked that the correct target branch is selected
- [x] I rebased the branch on the target branch and it can be merged
- [x] I ran the linter and it did pass
- [x] I checked for unused code / dead code / debug code
- [x] I checked that variables/functions have meaningful names
- [x] I checked that the behaviour is as the documentation/task describes and I tested it
- [x] I updated the docs / specifications if possible
- [x] I could explain all that code when someone wakes me up at 3am
- [x] I checked that the code considers failures and not just the happy path
- [x] There are no new dependencies OR I listed them and explained them below
- [x] PR introduces no breaking changes OR I listed them and described them below
- [x] I added/updated tests for new/modified unit-testable functions/helpers
- [x] I ran the tests and they did pass

## Summary

Hier scheint das Problem beim Filtern zu sein, dass die DisplayValues für die
archivierten Rows nicht nachgeneriert werden, dadurch greifen die Suchfunktionen
nicht.

2024-11-21 14:23 UTC, McHunkyTrunk requested changes
@hermann-p Es scheint noch irgendwas nicht in Ordnung zu sein. Die Filterung wird zwar angewandt, aber ich bekomme auch Ergebnisse mit den Zeilen, wo in der jeweiligen Spalte nichts eingetragen ist. Das betrifft sowohl archivierte als auch nicht-archivierte Zeilen.

Siehe beispielsweise BikeParts Testinstanz:
https://pdc-test.bikeparts.grud.de/de/tables/205

![image](https://github.com/user-attachments/assets/36647e28-e1e3-423b-b792-2ae29aa2eb9d)

2024-11-25 09:43 UTC, hermann-p commented
> [..] ich bekomme auch Ergebnisse mit den Zeilen, wo in der jeweiligen Spalte nichts eingetragen ist. Das betrifft sowohl archivierte als auch nicht-archivierte Zeilen.

War das vorher auch schon so?

2024-11-25 10:17 UTC, McHunkyTrunk commented
@hermann-p 
> War das vorher auch schon so?

Nein, ich habe die Live-Instanz gegengeprüft, und das ist es in Ordnung.

2024-11-25 12:58 UTC, hermann-p commented
> Nein, ich habe die Live-Instanz gegengeprüft, und das ist es in Ordnung.

Ok, das ist weird. Ich habe überhaupt nichts an den Filtern umgestellt…

2024-11-25 14:11 UTC, McHunkyTrunk commented
@hermann-p Probiere es doch gerne selbst aus. Du hast doch die Zugang zu den beiden Instanzen.

2024-11-26 07:46 UTC, hermann-p commented
> @hermann-p Probiere es doch gerne selbst aus. Du hast doch die Zugang zu den beiden Instanzen.

Das sollte nicht heißen ich glaube dir nicht, sondern dass ich das Verhalten unerklärlich und weird finde.

2025-01-08 11:36 UTC, hermann-p commented
Obsolete, gelöst in #413

2025-01-08 11:36 UTC, closed without merging